artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/c2bc3c3a31be4e7c885c10f1f45a7e23/artifacts
end_time: 1765141888783
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: c2bc3c3a31be4e7c885c10f1f45a7e23
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141888111
status: 3
tags: []
user_id: samwise
