artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/aba1e5c37ddf498d96e051d80b5b3c44/artifacts
end_time: 1764103353364
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: aba1e5c37ddf498d96e051d80b5b3c44
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103351842
status: 3
tags: []
user_id: samwise
