artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/1c2f3b59cddf43349354d11e37f05c92/artifacts
end_time: 1764105345207
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 1c2f3b59cddf43349354d11e37f05c92
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105344552
status: 3
tags: []
user_id: samwise
