artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/b8976d87726f47a0aace0a3e34f52355/artifacts
end_time: 1764105384510
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: b8976d87726f47a0aace0a3e34f52355
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105383928
status: 3
tags: []
user_id: samwise
