artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/0fe44a3486b34bd49403ebbf967e7320/artifacts
end_time: 1766088973390
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 0fe44a3486b34bd49403ebbf967e7320
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766088972428
status: 3
tags: []
user_id: samwise
