artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/09ce3d3ad93c42f39a95d39ea1d3d792/artifacts
end_time: 1764624084869
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 09ce3d3ad93c42f39a95d39ea1d3d792
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624083489
status: 3
tags: []
user_id: samwise
