artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/bbc3c3ce49e6463daa2651670d48a2ef/artifacts
end_time: 1764619596518
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: bbc3c3ce49e6463daa2651670d48a2ef
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619595727
status: 3
tags: []
user_id: samwise
