artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/db8a89ae558648b8b1a2f270ebb6c4be/artifacts
end_time: 1765141747339
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: db8a89ae558648b8b1a2f270ebb6c4be
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141746843
status: 3
tags: []
user_id: samwise
