artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/c15a50ae2a7346bd897a268ea531a60c/artifacts
end_time: 1764105268928
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: c15a50ae2a7346bd897a268ea531a60c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105268252
status: 3
tags: []
user_id: samwise
