artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/b1f8e1af67ea40649bd8c202354b0091/artifacts
end_time: 1764099864886
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: b1f8e1af67ea40649bd8c202354b0091
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099862103
status: 3
tags: []
user_id: samwise
