artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/850cee0ce17049a8bb9c3e8fb42dbf24/artifacts
end_time: 1764103766310
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 850cee0ce17049a8bb9c3e8fb42dbf24
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103764964
status: 3
tags: []
user_id: samwise
