artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/d636d3738f5d48eaadb4d05bb830ec78/artifacts
end_time: 1764103288204
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: d636d3738f5d48eaadb4d05bb830ec78
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103287616
status: 3
tags: []
user_id: samwise
