artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/43d728caa7164ea48aa0c80cef9e91a4/artifacts
end_time: 1764618632769
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 43d728caa7164ea48aa0c80cef9e91a4
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764618631896
status: 3
tags: []
user_id: samwise
