artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/677d40f2fdcd4e379ebac8d3ff1fab44/artifacts
end_time: 1764105533057
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 677d40f2fdcd4e379ebac8d3ff1fab44
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105532568
status: 3
tags: []
user_id: samwise
