artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/f35bed6a7e1743729dae1f48133a5ebd/artifacts
end_time: 1766089543229
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: f35bed6a7e1743729dae1f48133a5ebd
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089542488
status: 3
tags: []
user_id: samwise
