artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/47ee5bfd187e40f590a62720bad64121/artifacts
end_time: 1764095236332
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 47ee5bfd187e40f590a62720bad64121
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764095234790
status: 3
tags: []
user_id: samwise
