artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/ceeec9d32889485a9af7f89b905de988/artifacts
end_time: 1765140987604
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: ceeec9d32889485a9af7f89b905de988
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140986892
status: 3
tags: []
user_id: samwise
