artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/9c0130b60c4d4d9baa7cc6ff9084a768/artifacts
end_time: 1764097784436
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 9c0130b60c4d4d9baa7cc6ff9084a768
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764097783202
status: 3
tags: []
user_id: samwise
