artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/eb8c7e6a4a634037b0475ee81be3e783/artifacts
end_time: 1764098630386
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: eb8c7e6a4a634037b0475ee81be3e783
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098629089
status: 3
tags: []
user_id: samwise
