artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/d6c994c627e34a81a6c66bcb97166acc/artifacts
end_time: 1764102826967
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: d6c994c627e34a81a6c66bcb97166acc
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764102826415
status: 3
tags: []
user_id: samwise
