artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/a10d9eada948464e8d2d2600de8b35ca/artifacts
end_time: 1764623662852
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: a10d9eada948464e8d2d2600de8b35ca
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623662045
status: 3
tags: []
user_id: samwise
