artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/fd8bb7a23c004580a6083df6371adb24/artifacts
end_time: 1764619170151
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: fd8bb7a23c004580a6083df6371adb24
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619169758
status: 3
tags: []
user_id: samwise
