artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/a57f2c91c7d4444c85f33a872b96e8be/artifacts
end_time: 1764096417856
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: a57f2c91c7d4444c85f33a872b96e8be
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764096415415
status: 3
tags: []
user_id: samwise
