artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/256ff6df63f1427d8a6b87c8190ae2ee/artifacts
end_time: 1765140373510
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 256ff6df63f1427d8a6b87c8190ae2ee
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140372539
status: 3
tags: []
user_id: samwise
