artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/c60ce7cf3e5c4da1b566a8ca4203efa7/artifacts
end_time: 1766089261285
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: c60ce7cf3e5c4da1b566a8ca4203efa7
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089260485
status: 3
tags: []
user_id: samwise
