artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/956e10638cf54492b4e9e8d47b7be9aa/artifacts
end_time: 1764104948605
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 956e10638cf54492b4e9e8d47b7be9aa
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764104947654
status: 3
tags: []
user_id: samwise
