artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/5e68faa1b673485b93753d96556ec1bf/artifacts
end_time: 1764104098783
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 5e68faa1b673485b93753d96556ec1bf
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764104098148
status: 3
tags: []
user_id: samwise
