artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/3ee6e5cca8514bb4a8b63a9a7fbea484/artifacts
end_time: 1764105513879
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 3ee6e5cca8514bb4a8b63a9a7fbea484
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105513021
status: 3
tags: []
user_id: samwise
