artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/c910f9a38e864a9abcf9bcb59fab7485/artifacts
end_time: 1765141354313
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: c910f9a38e864a9abcf9bcb59fab7485
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141353555
status: 3
tags: []
user_id: samwise
