artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/d8e212fd7bfe4a389e39961012405d9e/artifacts
end_time: 1764619360131
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: d8e212fd7bfe4a389e39961012405d9e
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619359597
status: 3
tags: []
user_id: samwise
