artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/d9e284ad26254b2eafae1ee73320fc02/artifacts
end_time: 1765140224242
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: d9e284ad26254b2eafae1ee73320fc02
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140223355
status: 3
tags: []
user_id: samwise
