artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/be96905a0f1a4008b04fad34c3c2cc6a/artifacts
end_time: 1764105421603
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: be96905a0f1a4008b04fad34c3c2cc6a
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105421078
status: 3
tags: []
user_id: samwise
