artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/a634f9c3226d47219cbab92c64f0748a/artifacts
end_time: 1765142013347
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: a634f9c3226d47219cbab92c64f0748a
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765142012523
status: 3
tags: []
user_id: samwise
