artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/df22659a41ad4b13923f815c3dfdf059/artifacts
end_time: 1764098521941
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: df22659a41ad4b13923f815c3dfdf059
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098521298
status: 3
tags: []
user_id: samwise
