artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/957f0def5a394c3bb70fc7c62c5b10af/artifacts
end_time: 1764102792541
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 957f0def5a394c3bb70fc7c62c5b10af
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764102792057
status: 3
tags: []
user_id: samwise
