artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/a6caea83b448411d9d916eae8d026d3b/artifacts
end_time: 1764100727472
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: a6caea83b448411d9d916eae8d026d3b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100726914
status: 3
tags: []
user_id: samwise
