artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/558f60b2cd8043e89974fc7ba5f6361b/artifacts
end_time: 1764105542959
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 558f60b2cd8043e89974fc7ba5f6361b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105541372
status: 3
tags: []
user_id: samwise
