artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/3de5dc24e1eb4a3fbbe4f453acfd465b/artifacts
end_time: 1764099440413
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 3de5dc24e1eb4a3fbbe4f453acfd465b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099439419
status: 3
tags: []
user_id: samwise
