artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/10f483b4b1ab47a28722216a60cf1ab7/artifacts
end_time: 1765141092945
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 10f483b4b1ab47a28722216a60cf1ab7
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141091209
status: 3
tags: []
user_id: samwise
