artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/d28f781cb03841b9b6b9caf9c77a9063/artifacts
end_time: 1764623049210
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: d28f781cb03841b9b6b9caf9c77a9063
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623048421
status: 3
tags: []
user_id: samwise
