artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/9666c28c107f447d968bad890ab8c3dd/artifacts
end_time: 1764096743303
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 9666c28c107f447d968bad890ab8c3dd
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764096742083
status: 3
tags: []
user_id: samwise
