artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/46e5949e1df046c3a6d0d44aaed13bb8/artifacts
end_time: 1764623255428
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 46e5949e1df046c3a6d0d44aaed13bb8
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623253724
status: 3
tags: []
user_id: samwise
