artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/7df137bed9794e0b988c9d26d6e29a51/artifacts
end_time: 1764105248030
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 7df137bed9794e0b988c9d26d6e29a51
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105247323
status: 3
tags: []
user_id: samwise
