artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/ec5c75bc397e498ca0ac9b966cd729a4/artifacts
end_time: 1764098186860
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: ec5c75bc397e498ca0ac9b966cd729a4
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098186223
status: 3
tags: []
user_id: samwise
