artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/abe4ffe6e24541cc9cd127e950ca5afc/artifacts
end_time: 1764096118821
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: abe4ffe6e24541cc9cd127e950ca5afc
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764096115712
status: 3
tags: []
user_id: samwise
