artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/36d0f8241d6f4cd9b8c1dd097348bd34/artifacts
end_time: 1764618935214
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 36d0f8241d6f4cd9b8c1dd097348bd34
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764618934880
status: 3
tags: []
user_id: samwise
