artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/f3a60820ea7248c7a046b9ec8dc07504/artifacts
end_time: 1764619392566
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: f3a60820ea7248c7a046b9ec8dc07504
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619391717
status: 3
tags: []
user_id: samwise
