artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/23a2c338bdb2450e822dbd49fd6cb436/artifacts
end_time: 1764623684453
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 23a2c338bdb2450e822dbd49fd6cb436
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623683087
status: 3
tags: []
user_id: samwise
