artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/23cf3cbc76ce40d1b5a19b0ab3e6ee62/artifacts
end_time: 1764099776170
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 23cf3cbc76ce40d1b5a19b0ab3e6ee62
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099775011
status: 3
tags: []
user_id: samwise
