artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/206d21e4ea534a858e1bb5acfc551d6c/artifacts
end_time: 1764624214893
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 206d21e4ea534a858e1bb5acfc551d6c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624214368
status: 3
tags: []
user_id: samwise
