artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/2546ab7076884968b4c0e21bb2dcd9ac/artifacts
end_time: 1764706235386
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 2546ab7076884968b4c0e21bb2dcd9ac
run_name: rag_pipeline_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1764706224544
status: 3
tags: []
user_id: samwise
