artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/7fb060b8f2a24d7f92e6ad88119eb85a/artifacts
end_time: 1764624321016
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 7fb060b8f2a24d7f92e6ad88119eb85a
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624318683
status: 3
tags: []
user_id: samwise
