artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/4311de3d3a6f4499b379f4be89e8b418/artifacts
end_time: 1764623996415
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 4311de3d3a6f4499b379f4be89e8b418
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623995650
status: 3
tags: []
user_id: samwise
