artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/8bf93c8b7ed2411ebbb6664ac25e166d/artifacts
end_time: 1765142122196
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 8bf93c8b7ed2411ebbb6664ac25e166d
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765142121460
status: 3
tags: []
user_id: samwise
