artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/8233fdbd98554c3db7f81e86174c8e51/artifacts
end_time: 1764098118505
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 8233fdbd98554c3db7f81e86174c8e51
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098114754
status: 3
tags: []
user_id: samwise
