artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/8cd73940b5a24e6cb2174629bd434eb1/artifacts
end_time: 1764100364198
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 8cd73940b5a24e6cb2174629bd434eb1
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100361797
status: 3
tags: []
user_id: samwise
