artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/4dc68cf7f500441c9183e8c3cef48208/artifacts
end_time: 1764098950787
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 4dc68cf7f500441c9183e8c3cef48208
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098949781
status: 3
tags: []
user_id: samwise
