artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/40c6daa5d9c14c408e10a941c45f3a80/artifacts
end_time: 1765140690066
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 40c6daa5d9c14c408e10a941c45f3a80
run_name: vector_store_search
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140689795
status: 3
tags: []
user_id: samwise
