artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/3c125d20efdf47e585c2c967590d05c0/artifacts
end_time: 1764619185758
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 3c125d20efdf47e585c2c967590d05c0
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619184930
status: 3
tags: []
user_id: samwise
