artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/1e09d3ea2e8e40328fa6e464d7e73319/artifacts
end_time: 1764104082603
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 1e09d3ea2e8e40328fa6e464d7e73319
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764104082202
status: 3
tags: []
user_id: samwise
