artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/91aaf3afe6a849c295a396aa38a55b3f/artifacts
end_time: 1764100035316
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 91aaf3afe6a849c295a396aa38a55b3f
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100034717
status: 3
tags: []
user_id: samwise
