artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/3dd12c50eba845a88bbf95422e13e456/artifacts
end_time: 1766089101788
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 3dd12c50eba845a88bbf95422e13e456
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089100300
status: 3
tags: []
user_id: samwise
