artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/7c0fd431a0764ebdaa6a75f1b95f5c3d/artifacts
end_time: 1764103912382
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 7c0fd431a0764ebdaa6a75f1b95f5c3d
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103911713
status: 3
tags: []
user_id: samwise
