artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/32e1c0acb465483888ee5b1ae271bb9a/artifacts
end_time: 1766089117473
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 32e1c0acb465483888ee5b1ae271bb9a
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089115330
status: 3
tags: []
user_id: samwise
