artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/cdbf2c77e9a04c70898184973d0e6280/artifacts
end_time: 1764705412035
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: cdbf2c77e9a04c70898184973d0e6280
run_name: generate_cover_letter
source_name: ''
source_type: 4
source_version: ''
start_time: 1764705411796
status: 3
tags: []
user_id: samwise
