artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/f5e0590c11ef42118e8830c85cbb640e/artifacts
end_time: 1764103089328
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: f5e0590c11ef42118e8830c85cbb640e
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103088907
status: 3
tags: []
user_id: samwise
