artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/0d355e3a95c249d3a7ccfc30af60b558/artifacts
end_time: 1764105342456
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 0d355e3a95c249d3a7ccfc30af60b558
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105341871
status: 3
tags: []
user_id: samwise
