artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/715a643a4be14c9ea73e163c22bf771a/artifacts
end_time: 1764624185820
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 715a643a4be14c9ea73e163c22bf771a
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624184837
status: 3
tags: []
user_id: samwise
