artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/69a931f80f8f48caa6cf1c960acd2f5b/artifacts
end_time: 1764105530281
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 69a931f80f8f48caa6cf1c960acd2f5b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105529464
status: 3
tags: []
user_id: samwise
