artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/b26010e00a4344d3bde0d4cd5287303f/artifacts
end_time: 1765140520732
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: b26010e00a4344d3bde0d4cd5287303f
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140520194
status: 3
tags: []
user_id: samwise
