artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/75946531eedd4d4781e81ed4e7cce2ac/artifacts
end_time: 1764623681418
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 75946531eedd4d4781e81ed4e7cce2ac
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623680029
status: 3
tags: []
user_id: samwise
