artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/5464a93aa66e4a37bdb01a35a5a05047/artifacts
end_time: 1764097591303
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 5464a93aa66e4a37bdb01a35a5a05047
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764097590677
status: 3
tags: []
user_id: samwise
