artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/59a1db1dd59d4907a782d3bd505ed021/artifacts
end_time: 1765141276264
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 59a1db1dd59d4907a782d3bd505ed021
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141275548
status: 3
tags: []
user_id: samwise
