artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/2a471efec2c842d7bf6cc10fcb547ed0/artifacts
end_time: 1765142247086
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 2a471efec2c842d7bf6cc10fcb547ed0
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765142246207
status: 3
tags: []
user_id: samwise
