artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/08fde5696d8044c28c9acc95a0ff3ac5/artifacts
end_time: 1765140928586
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 08fde5696d8044c28c9acc95a0ff3ac5
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140927823
status: 3
tags: []
user_id: samwise
