artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/82adf959d267455c9e0686dedbd66729/artifacts
end_time: 1764099519468
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 82adf959d267455c9e0686dedbd66729
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099516133
status: 3
tags: []
user_id: samwise
