artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/df1de82e2f2741a2a8a00c8a8300b3e8/artifacts
end_time: 1764100346092
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: df1de82e2f2741a2a8a00c8a8300b3e8
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100345462
status: 3
tags: []
user_id: samwise
