artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/84cac539339f4b459b8994d0a0af73be/artifacts
end_time: 1764098143939
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 84cac539339f4b459b8994d0a0af73be
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098143239
status: 3
tags: []
user_id: samwise
