artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/c6e02daa3a4d493d9dfcb59a3223d59f/artifacts
end_time: 1764623655307
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: c6e02daa3a4d493d9dfcb59a3223d59f
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623654376
status: 3
tags: []
user_id: samwise
