artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/86f1076fc5864adfb0d7770346df0a4a/artifacts
end_time: 1764624274225
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 86f1076fc5864adfb0d7770346df0a4a
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624273563
status: 3
tags: []
user_id: samwise
