artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/f895d845e0a24300a8b3a1faf18e3539/artifacts
end_time: 1764096260757
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: f895d845e0a24300a8b3a1faf18e3539
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764096259615
status: 3
tags: []
user_id: samwise
