artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/51434aac9b8b49b785f9711c07e4ffe1/artifacts
end_time: 1765140057632
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 51434aac9b8b49b785f9711c07e4ffe1
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140055877
status: 3
tags: []
user_id: samwise
