artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/73f7596bc61341c1af3410fee411c09c/artifacts
end_time: 1764096808517
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 73f7596bc61341c1af3410fee411c09c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764096807091
status: 3
tags: []
user_id: samwise
