artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/bf40928fa3bf45d8ba9e47245eb862ad/artifacts
end_time: 1764618711499
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: bf40928fa3bf45d8ba9e47245eb862ad
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764618710836
status: 3
tags: []
user_id: samwise
