artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/827786605f9d44f484c4cbb2ecb7c88d/artifacts
end_time: 1764105280992
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 827786605f9d44f484c4cbb2ecb7c88d
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105280466
status: 3
tags: []
user_id: samwise
