artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/648a684069cf4ac2a044334bbd3b4ecc/artifacts
end_time: 1764095266301
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 648a684069cf4ac2a044334bbd3b4ecc
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764095265612
status: 3
tags: []
user_id: samwise
