artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/7f006bfcd3724bc78f8a8f1557debdfd/artifacts
end_time: 1764098469318
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 7f006bfcd3724bc78f8a8f1557debdfd
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098468563
status: 3
tags: []
user_id: samwise
