artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/bb05a8a809234e4290bef8c3d0c61997/artifacts
end_time: 1765140628981
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: bb05a8a809234e4290bef8c3d0c61997
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140627988
status: 3
tags: []
user_id: samwise
