artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/a3a4fa7bb73a495382bbb3853d666381/artifacts
end_time: 1764097075372
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: a3a4fa7bb73a495382bbb3853d666381
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764097072259
status: 3
tags: []
user_id: samwise
