artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/0ee083f7668b4ef5a37ac48285d2f82f/artifacts
end_time: 1764626715469
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 0ee083f7668b4ef5a37ac48285d2f82f
run_name: retrieve_similar_jobs
source_name: ''
source_type: 4
source_version: ''
start_time: 1764626714668
status: 3
tags: []
user_id: samwise
