artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/6895df230e254d43b997a58c4f60ca4a/artifacts
end_time: 1764096815057
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 6895df230e254d43b997a58c4f60ca4a
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764096813889
status: 3
tags: []
user_id: samwise
