artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/31a176b0dcf7412aa321f6d5e34e7966/artifacts
end_time: 1764096943807
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 31a176b0dcf7412aa321f6d5e34e7966
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764096943162
status: 3
tags: []
user_id: samwise
