artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/dbb904ea3fa249c6af4a8a51c3608065/artifacts
end_time: 1766089879594
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: dbb904ea3fa249c6af4a8a51c3608065
run_name: vector_store_search
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089879225
status: 3
tags: []
user_id: samwise
