artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/b60d0c4b4c5e4a57864c4b389fcb4812/artifacts
end_time: 1764099923534
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: b60d0c4b4c5e4a57864c4b389fcb4812
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099922924
status: 3
tags: []
user_id: samwise
