artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/a9dc20e32ef24047b82b95b0b8414c4c/artifacts
end_time: 1764102907724
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: a9dc20e32ef24047b82b95b0b8414c4c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764102907301
status: 3
tags: []
user_id: samwise
