artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/54db33b4572c4060b96b65dcf5ad66d9/artifacts
end_time: 1764105193988
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 54db33b4572c4060b96b65dcf5ad66d9
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105192996
status: 3
tags: []
user_id: samwise
