artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/4ab9a4aef51b43dfae284d8799ba53e3/artifacts
end_time: 1764102759967
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 4ab9a4aef51b43dfae284d8799ba53e3
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764102759532
status: 3
tags: []
user_id: samwise
