artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/64dc02ef03484c4b8d442600199fa84e/artifacts
end_time: 1764627542107
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 64dc02ef03484c4b8d442600199fa84e
run_name: vector_store_search
source_name: ''
source_type: 4
source_version: ''
start_time: 1764627541663
status: 3
tags: []
user_id: samwise
