artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/19636ef18cfd4c6187481aad9592cb45/artifacts
end_time: 1764623957397
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 19636ef18cfd4c6187481aad9592cb45
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623956262
status: 3
tags: []
user_id: samwise
