artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/922e9499165c40a8aa231afafc7d83bb/artifacts
end_time: 1764096839521
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 922e9499165c40a8aa231afafc7d83bb
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764096836579
status: 3
tags: []
user_id: samwise
