artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/6a7f8acec84d4695974883cd67fb0901/artifacts
end_time: 1764619728057
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 6a7f8acec84d4695974883cd67fb0901
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619727453
status: 3
tags: []
user_id: samwise
