artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/bc8c702d8f81466694a405098b5beaa5/artifacts
end_time: 1764104982566
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: bc8c702d8f81466694a405098b5beaa5
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764104981603
status: 3
tags: []
user_id: samwise
