artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/21280505dde04d7fadb1518d680b2b17/artifacts
end_time: 1764100863275
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 21280505dde04d7fadb1518d680b2b17
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100862672
status: 3
tags: []
user_id: samwise
