artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/a25551d8e3f840c99bca639bbb878207/artifacts
end_time: 1764105466674
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: a25551d8e3f840c99bca639bbb878207
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105466183
status: 3
tags: []
user_id: samwise
