artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/959debb2712f440cb5b1223633abe4d9/artifacts
end_time: 1764103808840
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 959debb2712f440cb5b1223633abe4d9
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103807709
status: 3
tags: []
user_id: samwise
