artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/5b74671caa584d0f9ca52a715ac56dfc/artifacts
end_time: 1764103687006
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 5b74671caa584d0f9ca52a715ac56dfc
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103685964
status: 3
tags: []
user_id: samwise
