artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/f8c5d473b6cb4c269124adedd1913030/artifacts
end_time: 1765141060877
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: f8c5d473b6cb4c269124adedd1913030
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141060216
status: 3
tags: []
user_id: samwise
