artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/f2dce80ff1a141d3b647e9f2c167482c/artifacts
end_time: 1765141736336
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: f2dce80ff1a141d3b647e9f2c167482c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141735544
status: 3
tags: []
user_id: samwise
