artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/dc334d9e9a46436c8fc4042e49d849e5/artifacts
end_time: 1764626355086
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: dc334d9e9a46436c8fc4042e49d849e5
run_name: generate_cover_letter
source_name: ''
source_type: 4
source_version: ''
start_time: 1764626335287
status: 3
tags: []
user_id: samwise
