artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/de95e98c47f74f4383f6cddb99b5f91f/artifacts
end_time: 1764619407431
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: de95e98c47f74f4383f6cddb99b5f91f
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619406573
status: 3
tags: []
user_id: samwise
