artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/d5d7d44bf8e24545b64757d37d1abb72/artifacts
end_time: 1764098667388
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: d5d7d44bf8e24545b64757d37d1abb72
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098666331
status: 3
tags: []
user_id: samwise
