artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/cf579f7c3ce14973bda97c2fc9b8ecd3/artifacts
end_time: 1764099823676
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: cf579f7c3ce14973bda97c2fc9b8ecd3
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099822231
status: 3
tags: []
user_id: samwise
