artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/36b412b66ae346439fd94db98ce1b725/artifacts
end_time: 1764105556398
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 36b412b66ae346439fd94db98ce1b725
run_name: qdrant_ingestion
source_name: ''
source_type: 4
source_version: ''
start_time: 1764104944801
status: 3
tags: []
user_id: samwise
