artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/50e1d058c7ae42019ee364994b70dcf7/artifacts
end_time: 1766089304523
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 50e1d058c7ae42019ee364994b70dcf7
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089304179
status: 3
tags: []
user_id: samwise
