artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/c9b65573580a4c63a1c71cdbb18ea6fa/artifacts
end_time: 1766089744099
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: c9b65573580a4c63a1c71cdbb18ea6fa
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089742829
status: 3
tags: []
user_id: samwise
