artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/0c1e0fec65cb4e9ba8e50ad43c601e6c/artifacts
end_time: 1764627519602
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 0c1e0fec65cb4e9ba8e50ad43c601e6c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764627518260
status: 3
tags: []
user_id: samwise
