artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/6fe6c9597d4246c987a0e5bd498756fd/artifacts
end_time: 1764099630570
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 6fe6c9597d4246c987a0e5bd498756fd
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099630105
status: 3
tags: []
user_id: samwise
