artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/ce7a8a6d837645c3a87610fce375fc29/artifacts
end_time: 1764624361119
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: ce7a8a6d837645c3a87610fce375fc29
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624359988
status: 3
tags: []
user_id: samwise
