artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/495113a8c7f84992afdf3ec670da10ab/artifacts
end_time: 1765142167830
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 495113a8c7f84992afdf3ec670da10ab
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765142167262
status: 3
tags: []
user_id: samwise
