artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/508e6426e0fe4c658ae30fe6fb68b7f0/artifacts
end_time: 1764095951210
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 508e6426e0fe4c658ae30fe6fb68b7f0
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764095950153
status: 3
tags: []
user_id: samwise
