artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/03bbd2442f6a45c0ab17b164fafafb73/artifacts
end_time: 1764097792437
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 03bbd2442f6a45c0ab17b164fafafb73
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764097791107
status: 3
tags: []
user_id: samwise
