artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/62a7b3f506ec4e07a1ad70a57a15c210/artifacts
end_time: 1766089285760
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 62a7b3f506ec4e07a1ad70a57a15c210
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089284803
status: 3
tags: []
user_id: samwise
