artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/de124ce998ca46fdabf50952455c060c/artifacts
end_time: 1765141789327
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: de124ce998ca46fdabf50952455c060c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141788574
status: 3
tags: []
user_id: samwise
