artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/572a6dc447ca4ce0bccd0e1bab044664/artifacts
end_time: 1764103666295
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 572a6dc447ca4ce0bccd0e1bab044664
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103665727
status: 3
tags: []
user_id: samwise
