artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/66a06dc30c104a7fad8cf8d0079a61e0/artifacts
end_time: 1764100466806
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 66a06dc30c104a7fad8cf8d0079a61e0
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100465233
status: 3
tags: []
user_id: samwise
