artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/1645436be10b4d9582ab8e0f2ac62bd9/artifacts
end_time: 1764102900406
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 1645436be10b4d9582ab8e0f2ac62bd9
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764102900020
status: 3
tags: []
user_id: samwise
