artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/49e0e34fa7c144aa9ebd9a8e4945c475/artifacts
end_time: 1764098174696
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 49e0e34fa7c144aa9ebd9a8e4945c475
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098174099
status: 3
tags: []
user_id: samwise
