artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/a7553be9a9b6474eb7cbb85ec778a6b5/artifacts
end_time: 1764623811250
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: a7553be9a9b6474eb7cbb85ec778a6b5
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623810260
status: 3
tags: []
user_id: samwise
