artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/2edcc37f7d4f436bab28f193f632f028/artifacts
end_time: 1764100080219
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 2edcc37f7d4f436bab28f193f632f028
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100079511
status: 3
tags: []
user_id: samwise
