artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/dca23b5f643d4007af47f2a3ec7d173c/artifacts
end_time: 1764098328966
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: dca23b5f643d4007af47f2a3ec7d173c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098328060
status: 3
tags: []
user_id: samwise
