artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/6c319d64d87a4ee692bdcc7b5d909d6e/artifacts
end_time: 1764099613811
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 6c319d64d87a4ee692bdcc7b5d909d6e
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099613225
status: 3
tags: []
user_id: samwise
