artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/15d2b7f70f49411cb03fb32c27284aab/artifacts
end_time: 1764705488641
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 15d2b7f70f49411cb03fb32c27284aab
run_name: vector_store_search
source_name: ''
source_type: 4
source_version: ''
start_time: 1764705488265
status: 3
tags: []
user_id: samwise
