artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/d7f64b2c9182469cb7bf69597e73bd69/artifacts
end_time: 1764103030260
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: d7f64b2c9182469cb7bf69597e73bd69
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103029776
status: 3
tags: []
user_id: samwise
