artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/d1a35c02fa8f4f98a9b9456abd31e7cc/artifacts
end_time: 1764098553440
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: d1a35c02fa8f4f98a9b9456abd31e7cc
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098552779
status: 3
tags: []
user_id: samwise
