artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/b36aba64f886493187ffea27fe799c67/artifacts
end_time: 1765140530557
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: b36aba64f886493187ffea27fe799c67
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140529767
status: 3
tags: []
user_id: samwise
