artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/c73edfb7096b419cb9766517a01a067b/artifacts
end_time: 1764623086954
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: c73edfb7096b419cb9766517a01a067b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623086345
status: 3
tags: []
user_id: samwise
