artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/8dfbcbd3b1e048fb9f59b07a38ee06ff/artifacts
end_time: 1764703547162
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 8dfbcbd3b1e048fb9f59b07a38ee06ff
run_name: retrieve_similar_jobs
source_name: ''
source_type: 4
source_version: ''
start_time: 1764703544465
status: 3
tags: []
user_id: samwise
