artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/93db7d20a9fd40a8a898e1334f0408f0/artifacts
end_time: 1765140968484
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 93db7d20a9fd40a8a898e1334f0408f0
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140967797
status: 3
tags: []
user_id: samwise
