artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/3d7fa22ad3c645e8b61bc942cd05172c/artifacts
end_time: 1765140657425
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 3d7fa22ad3c645e8b61bc942cd05172c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140656552
status: 3
tags: []
user_id: samwise
