artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/1f02dcd462cf4da8a549260842fba756/artifacts
end_time: 1764097466044
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 1f02dcd462cf4da8a549260842fba756
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764097465252
status: 3
tags: []
user_id: samwise
