artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/cd02a0d3d8d646a2ac790f480224ddae/artifacts
end_time: 1764618917585
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: cd02a0d3d8d646a2ac790f480224ddae
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764618915934
status: 3
tags: []
user_id: samwise
