artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/40b304ab6b1a4c9e9182dea5e484ae91/artifacts
end_time: 1764097493924
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 40b304ab6b1a4c9e9182dea5e484ae91
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764097493449
status: 3
tags: []
user_id: samwise
