artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/6c53f7c4792d4d7cbfce62646874951f/artifacts
end_time: 1765141949435
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 6c53f7c4792d4d7cbfce62646874951f
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141948706
status: 3
tags: []
user_id: samwise
