artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/7db4b1b5c8e04f77a78b00aabee54811/artifacts
end_time: 1764623141488
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 7db4b1b5c8e04f77a78b00aabee54811
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623140699
status: 3
tags: []
user_id: samwise
