artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/fceeb91fda05474da17719d322ded656/artifacts
end_time: 1764623502696
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: fceeb91fda05474da17719d322ded656
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623502198
status: 3
tags: []
user_id: samwise
