artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/253a9c27aaa348c6a00076e6a31ec6ef/artifacts
end_time: 1764624242844
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 253a9c27aaa348c6a00076e6a31ec6ef
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624241932
status: 3
tags: []
user_id: samwise
