artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/94f383b9f55c40979a5aa1c582cb3aa4/artifacts
end_time: 1764100096824
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 94f383b9f55c40979a5aa1c582cb3aa4
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100095566
status: 3
tags: []
user_id: samwise
