artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/32083ab2cf4a4ad8a7638ce007c7f1cc/artifacts
end_time: 1765141460920
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 32083ab2cf4a4ad8a7638ce007c7f1cc
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141459452
status: 3
tags: []
user_id: samwise
