artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/aa7e7cae5ea94154854a2c1a0f4aa945/artifacts
end_time: 1765140238466
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: aa7e7cae5ea94154854a2c1a0f4aa945
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140237386
status: 3
tags: []
user_id: samwise
