artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/fd5e598c1102430c9af4c9f516a8163d/artifacts
end_time: 1764103182041
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: fd5e598c1102430c9af4c9f516a8163d
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103180891
status: 3
tags: []
user_id: samwise
