artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/18b50a19dbd246f1bfb4b975be0a9cdf/artifacts
end_time: 1764619204970
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 18b50a19dbd246f1bfb4b975be0a9cdf
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619204371
status: 3
tags: []
user_id: samwise
