artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/b36afd7b0e9842dab00da3c616b94212/artifacts
end_time: 1766089782515
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: b36afd7b0e9842dab00da3c616b94212
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089781593
status: 3
tags: []
user_id: samwise
