artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/109505df5faf4cdcbeb09d3eeb8e1f45/artifacts
end_time: 1765140258375
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 109505df5faf4cdcbeb09d3eeb8e1f45
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140257669
status: 3
tags: []
user_id: samwise
