artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/693dedab0c9b4a01b37871b85fc9f576/artifacts
end_time: 1764623206713
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 693dedab0c9b4a01b37871b85fc9f576
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623204520
status: 3
tags: []
user_id: samwise
