artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/3bec6e00446b4e5cbaf24a461121192b/artifacts
end_time: 1764095425698
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 3bec6e00446b4e5cbaf24a461121192b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764095424902
status: 3
tags: []
user_id: samwise
