artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/234d1fb1cf134db2a564d5a1e307d875/artifacts
end_time: 1764096499539
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 234d1fb1cf134db2a564d5a1e307d875
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764096497521
status: 3
tags: []
user_id: samwise
