artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/eacd4e0fbd784dfd968b648e5cc6bc85/artifacts
end_time: 1764104068457
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: eacd4e0fbd784dfd968b648e5cc6bc85
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764104067388
status: 3
tags: []
user_id: samwise
