artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/6eac90cd2c7c4f1dbc14c45c7181b9d2/artifacts
end_time: 1764619593727
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 6eac90cd2c7c4f1dbc14c45c7181b9d2
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619593125
status: 3
tags: []
user_id: samwise
