artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/f9a686d1f10949ea8154d358abb0f7bc/artifacts
end_time: 1766089346965
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: f9a686d1f10949ea8154d358abb0f7bc
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089346194
status: 3
tags: []
user_id: samwise
