artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/5a0af326508d44b7ac9a34362bcd0bbe/artifacts
end_time: 1765140538010
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 5a0af326508d44b7ac9a34362bcd0bbe
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140537203
status: 3
tags: []
user_id: samwise
