artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/c9f8a5e6758449ab821b8e4f0bf6bfb7/artifacts
end_time: 1764103461328
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: c9f8a5e6758449ab821b8e4f0bf6bfb7
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103460166
status: 3
tags: []
user_id: samwise
