artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/26adb1fcec4141bcafdd1bd6e366ffe4/artifacts
end_time: 1764624075766
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 26adb1fcec4141bcafdd1bd6e366ffe4
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624074840
status: 3
tags: []
user_id: samwise
