artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/0a8e8bf112f34a86b0d1b399ed34b9f3/artifacts
end_time: 1764538474090
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 0a8e8bf112f34a86b0d1b399ed34b9f3
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764538472868
status: 3
tags: []
user_id: samwise
