artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/4e4c8a69d6a74c9399d32a2cb8dbd925/artifacts
end_time: 1764105055789
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 4e4c8a69d6a74c9399d32a2cb8dbd925
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105055015
status: 3
tags: []
user_id: samwise
