artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/1ac7bb22785d49a19b2a699b0b0a14cd/artifacts
end_time: 1764105214884
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 1ac7bb22785d49a19b2a699b0b0a14cd
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105214020
status: 3
tags: []
user_id: samwise
