artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/cd71fd348c854fb3bc4949303af79df2/artifacts
end_time: 1766089616259
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: cd71fd348c854fb3bc4949303af79df2
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089615383
status: 3
tags: []
user_id: samwise
