artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/9b54373c37064fce8e51cafec12a65e4/artifacts
end_time: 1765141113604
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 9b54373c37064fce8e51cafec12a65e4
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141112878
status: 3
tags: []
user_id: samwise
