artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/4215f3da05fa4baf9ffb2b3e55a13425/artifacts
end_time: 1765142072543
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 4215f3da05fa4baf9ffb2b3e55a13425
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765142071868
status: 3
tags: []
user_id: samwise
