artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/c0ad49c3ec8c448daa95a743bc27af38/artifacts
end_time: 1764098966366
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: c0ad49c3ec8c448daa95a743bc27af38
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098965326
status: 3
tags: []
user_id: samwise
