artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/410a7d3f123840d6a4bcb8fad3d8c710/artifacts
end_time: 1764099406594
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 410a7d3f123840d6a4bcb8fad3d8c710
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099406051
status: 3
tags: []
user_id: samwise
