artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/8eb5c2d63f7a4ff4b059de53dea99b6b/artifacts
end_time: 1764097845469
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 8eb5c2d63f7a4ff4b059de53dea99b6b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764097844892
status: 3
tags: []
user_id: samwise
