artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/346d18afd4ce4b7aaa0bad119a3312e3/artifacts
end_time: 1764619524344
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 346d18afd4ce4b7aaa0bad119a3312e3
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619523576
status: 3
tags: []
user_id: samwise
