artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/0e35bdc4ed6146288e29b0ca7923cd68/artifacts
end_time: 1764103310857
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 0e35bdc4ed6146288e29b0ca7923cd68
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103310495
status: 3
tags: []
user_id: samwise
