artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/23dddf29b83b47d6a338d290a4ab3ceb/artifacts
end_time: 1764619473656
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 23dddf29b83b47d6a338d290a4ab3ceb
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619472889
status: 3
tags: []
user_id: samwise
