artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/3761c860a77d437493afbe65aa9b00bf/artifacts
end_time: 1764099411686
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 3761c860a77d437493afbe65aa9b00bf
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099411269
status: 3
tags: []
user_id: samwise
