artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/a1b35a27cd294a9aa6d9627a555ef558/artifacts
end_time: 1764627541650
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: a1b35a27cd294a9aa6d9627a555ef558
run_name: insert_embeddings
source_name: ''
source_type: 4
source_version: ''
start_time: 1764627541486
status: 3
tags: []
user_id: samwise
