artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/ecf31838f5654c318b4bb9c8b2ed590d/artifacts
end_time: 1764100780643
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: ecf31838f5654c318b4bb9c8b2ed590d
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100780123
status: 3
tags: []
user_id: samwise
