artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/82d657a73acc4b2fb2a00a7e7383c425/artifacts
end_time: 1764103261001
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 82d657a73acc4b2fb2a00a7e7383c425
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103260412
status: 3
tags: []
user_id: samwise
