artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/b354515feefd4343b50f955d19fcb6ad/artifacts
end_time: 1764623442174
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: b354515feefd4343b50f955d19fcb6ad
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623441009
status: 3
tags: []
user_id: samwise
