artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/593333a2ab994133855ebc41bc847cee/artifacts
end_time: 1764095908742
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 593333a2ab994133855ebc41bc847cee
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764095907483
status: 3
tags: []
user_id: samwise
