artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/1c94566e34364cbab37b533c4fa191c7/artifacts
end_time: 1766089171771
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 1c94566e34364cbab37b533c4fa191c7
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089170430
status: 3
tags: []
user_id: samwise
