artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/8fa6b604329d4e4d9a8a366b605025cb/artifacts
end_time: 1764105288312
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 8fa6b604329d4e4d9a8a366b605025cb
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105287650
status: 3
tags: []
user_id: samwise
