artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/9329eb078e3b4be4aee25bd360d632d5/artifacts
end_time: 1764100636977
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 9329eb078e3b4be4aee25bd360d632d5
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100636411
status: 3
tags: []
user_id: samwise
