artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/dda9e83e3a2a4f598ce30b4967b70fdf/artifacts
end_time: 1764097426209
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: dda9e83e3a2a4f598ce30b4967b70fdf
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764097425262
status: 3
tags: []
user_id: samwise
