artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/3c7225dfb853494ea6bda3707505c3e4/artifacts
end_time: 1764100359392
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 3c7225dfb853494ea6bda3707505c3e4
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100358783
status: 3
tags: []
user_id: samwise
