artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/9f4804bb100f43bfabe2b0bb5355bf6d/artifacts
end_time: 1764098290305
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 9f4804bb100f43bfabe2b0bb5355bf6d
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098288273
status: 3
tags: []
user_id: samwise
