artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/11f03a06e27f43888ad4edf544abbce7/artifacts
end_time: 1764619233755
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 11f03a06e27f43888ad4edf544abbce7
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619233037
status: 3
tags: []
user_id: samwise
