artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/b69be58bb2f54ee38de634b4c49bbb05/artifacts
end_time: 1764100671650
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: b69be58bb2f54ee38de634b4c49bbb05
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100670687
status: 3
tags: []
user_id: samwise
