artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/047763c5c7e04a1db2853be7c70f7fa1/artifacts
end_time: 1766089039698
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 047763c5c7e04a1db2853be7c70f7fa1
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089038408
status: 3
tags: []
user_id: samwise
