# === Global Config for Career Assistant ===

# --- Paths ---
data_paths:
  raw_data: "career_assistant/data/raw/"
  processed_data: "career_assistant/data/processed/"
  vector_store: "career_assistant/data/vector_store/default/"
  model_dir: "career_assistant/artifacts/models/"
  qdrant_storage: "./qdrant_storage/"

# --- Embeddings ---
embedding_model: "sentence-transformers/intfloat/e5-base-v2"
embedding_dim: 384

# --- Qdrant Vector Database ---
qdrant:
  host: "localhost"
  port: 6333
  collection_name: "career_vectors"
  distance_metric: "Cosine"
  recreate_collection: false

# --- Semantic Matching ---
semantic_matching:
  batch_size: 64
  top_n: 5
  similarity_threshold: 0.75
  use_qdrant: true
  save_embeddings: true

# --- RAG Pipeline ---
retriever:
  top_k: 5
  similarity_metric: "cosine"

generator:
  model_name: "google/flan-t5-small"
  max_length: 200
  min_length: 60

# --- Docker ---
docker:
  image_name: "career_assistant"
  container_port: 8080
  host_port: 8080

# --- Logging ---
logging:
  level: "INFO"
  log_to_file: true
  log_file: "logs/app.log"

# --- Environment ---
environment:
  dev: true
  staging: false
  production: false