artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/ef9362cb4ff443a8b01b78c539bba4d7/artifacts
end_time: 1766089142802
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: ef9362cb4ff443a8b01b78c539bba4d7
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089141845
status: 3
tags: []
user_id: samwise
