artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/1cf31d4c8bd448e0bf7a67df2985df05/artifacts
end_time: 1765141779267
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 1cf31d4c8bd448e0bf7a67df2985df05
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141778651
status: 3
tags: []
user_id: samwise
