artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/74a1252ac8bc4b0c994fbe4a8d238ca5/artifacts
end_time: 1764623823599
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 74a1252ac8bc4b0c994fbe4a8d238ca5
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623819714
status: 3
tags: []
user_id: samwise
