artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/d74dc9fa9b87411f869a466194bd4ede/artifacts
end_time: 1765141098066
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: d74dc9fa9b87411f869a466194bd4ede
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141097205
status: 3
tags: []
user_id: samwise
