artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/2345c79d68444fdcb15b6442de38f63c/artifacts
end_time: 1764099969938
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 2345c79d68444fdcb15b6442de38f63c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099967705
status: 3
tags: []
user_id: samwise
