artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/bf199e05cdea40e6b2c2f270c6a7eeba/artifacts
end_time: 1764619333215
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: bf199e05cdea40e6b2c2f270c6a7eeba
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619332482
status: 3
tags: []
user_id: samwise
