artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/c325f1b47e2f483cb86497baa676591b/artifacts
end_time: 1764095820869
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: c325f1b47e2f483cb86497baa676591b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764095818163
status: 3
tags: []
user_id: samwise
