artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/3a7fb3b71c6245c3b9ae8111b0e6960c/artifacts
end_time: 1764103951779
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 3a7fb3b71c6245c3b9ae8111b0e6960c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103951172
status: 3
tags: []
user_id: samwise
