artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/5667229bf0f44b1bbe07ab2b363cce7a/artifacts
end_time: 1764105320387
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 5667229bf0f44b1bbe07ab2b363cce7a
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105319849
status: 3
tags: []
user_id: samwise
