artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/8046f5b4d6434d22a4ae0453b3ffde68/artifacts
end_time: 1764624046041
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 8046f5b4d6434d22a4ae0453b3ffde68
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624044982
status: 3
tags: []
user_id: samwise
