artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/2e16f6ac89204a9f8b29e300c0fb19ed/artifacts
end_time: 1765141072622
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 2e16f6ac89204a9f8b29e300c0fb19ed
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141071733
status: 3
tags: []
user_id: samwise
