artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/8479a82d1fe54aab9ff6dd33174cc5ed/artifacts
end_time: 1764627665858
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 8479a82d1fe54aab9ff6dd33174cc5ed
run_name: embed_query
source_name: ''
source_type: 4
source_version: ''
start_time: 1764627665322
status: 3
tags: []
user_id: samwise
