artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/dfb4d3d9513b4bcf891c05c857cdf1e0/artifacts
end_time: 1765140523132
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: dfb4d3d9513b4bcf891c05c857cdf1e0
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140522350
status: 3
tags: []
user_id: samwise
