artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/90d3d32c62c34d0594e3abdff5c398f1/artifacts
end_time: 1764105238643
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 90d3d32c62c34d0594e3abdff5c398f1
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105237993
status: 3
tags: []
user_id: samwise
