artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/58bcd63ec14d43428e5de4d0cc5b9242/artifacts
end_time: 1764623344560
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 58bcd63ec14d43428e5de4d0cc5b9242
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623343006
status: 3
tags: []
user_id: samwise
