artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/ed2cd1cfb84f4be8b48d3af8d590b9fa/artifacts
end_time: 1764707839515
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: ed2cd1cfb84f4be8b48d3af8d590b9fa
run_name: vector_store_search
source_name: ''
source_type: 4
source_version: ''
start_time: 1764707838889
status: 3
tags: []
user_id: samwise
