artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/f8cb98f02b744127a3e4ece4ae3e1369/artifacts
end_time: 1764619719155
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: f8cb98f02b744127a3e4ece4ae3e1369
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619718615
status: 3
tags: []
user_id: samwise
