artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/7b84e03040484ad3af2149ed47b8ba8b/artifacts
end_time: 1764105073175
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 7b84e03040484ad3af2149ed47b8ba8b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105072360
status: 3
tags: []
user_id: samwise
