artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/33c9bf1c2aed41cb844b701ca0aad948/artifacts
end_time: 1764103935604
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 33c9bf1c2aed41cb844b701ca0aad948
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103934582
status: 3
tags: []
user_id: samwise
