artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/ebfdcadb53c845bf8388e63730d1cd45/artifacts
end_time: 1764099763743
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: ebfdcadb53c845bf8388e63730d1cd45
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099763121
status: 3
tags: []
user_id: samwise
