artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/613f3d335ef2432ebe2e9faa47130f0c/artifacts
end_time: 1764099532266
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 613f3d335ef2432ebe2e9faa47130f0c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099531791
status: 3
tags: []
user_id: samwise
