artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/315faac980ef47889d6b215830ba8b78/artifacts
end_time: 1765142195442
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 315faac980ef47889d6b215830ba8b78
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765142193052
status: 3
tags: []
user_id: samwise
