artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/2e740a7f810e4ab6990d0c1e0bf181fa/artifacts
end_time: 1764624190242
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 2e740a7f810e4ab6990d0c1e0bf181fa
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624189486
status: 3
tags: []
user_id: samwise
