artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/7ae93e7902724d9bb6c9af5db1267ead/artifacts
end_time: 1764619151292
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 7ae93e7902724d9bb6c9af5db1267ead
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619150708
status: 3
tags: []
user_id: samwise
