artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/01eb6eb3385b448fb6f01bf826a2719b/artifacts
end_time: 1765141061611
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 01eb6eb3385b448fb6f01bf826a2719b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141060891
status: 3
tags: []
user_id: samwise
