artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/76f19f560bef468492f9e48eb5ab61b1/artifacts
end_time: 1764619082700
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 76f19f560bef468492f9e48eb5ab61b1
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619074911
status: 3
tags: []
user_id: samwise
