artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/5d97283834b5424fa8f2b2c4f609fe5b/artifacts
end_time: 1764099514021
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 5d97283834b5424fa8f2b2c4f609fe5b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099512871
status: 3
tags: []
user_id: samwise
