artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/d141aaf3f8db4c1fbfa78f3ecf8a0e83/artifacts
end_time: 1766089866520
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: d141aaf3f8db4c1fbfa78f3ecf8a0e83
run_name: vector_store_search
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089866106
status: 3
tags: []
user_id: samwise
