artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/8ae138582d434d49b332b9fd1bba3839/artifacts
end_time: 1766089686119
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 8ae138582d434d49b332b9fd1bba3839
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089682611
status: 3
tags: []
user_id: samwise
