artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/739f0f969ced4c69b52bf94a7593fcd9/artifacts
end_time: 1764105408812
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 739f0f969ced4c69b52bf94a7593fcd9
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105408140
status: 3
tags: []
user_id: samwise
