artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/f0596dc6d0a94640ac6365ac533b2c53/artifacts
end_time: 1765142080912
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: f0596dc6d0a94640ac6365ac533b2c53
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765142080256
status: 3
tags: []
user_id: samwise
