artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/4997f246d9d0438da0594e0af2b0ddb1/artifacts
end_time: 1764096564114
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 4997f246d9d0438da0594e0af2b0ddb1
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764096563618
status: 3
tags: []
user_id: samwise
