artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/d1420c4794bf4165830ff9ae8225ebcd/artifacts
end_time: 1764104090066
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: d1420c4794bf4165830ff9ae8225ebcd
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764104089557
status: 3
tags: []
user_id: samwise
