artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/754ea7cca15d4cefb51630c419e5e4f4/artifacts
end_time: null
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 754ea7cca15d4cefb51630c419e5e4f4
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764537090625
status: 1
tags: []
user_id: samwise
