artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/8c414d7813b34b9f9dd03057bceeea2b/artifacts
end_time: 1764099699117
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 8c414d7813b34b9f9dd03057bceeea2b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099697357
status: 3
tags: []
user_id: samwise
