artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/ac166c2e22cb41a297d28c428e1871a7/artifacts
end_time: 1764104066218
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: ac166c2e22cb41a297d28c428e1871a7
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764104065026
status: 3
tags: []
user_id: samwise
