artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/ab69210b8b494c3da59ff18c23c3ad47/artifacts
end_time: 1764095807507
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: ab69210b8b494c3da59ff18c23c3ad47
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764095806885
status: 3
tags: []
user_id: samwise
