artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/8b54a54cddde4f67a6099e5271f92634/artifacts
end_time: 1765141186295
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 8b54a54cddde4f67a6099e5271f92634
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141185588
status: 3
tags: []
user_id: samwise
