artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/029f1abad9894b03bae33bd6f580d68a/artifacts
end_time: 1765141182075
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 029f1abad9894b03bae33bd6f580d68a
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141181472
status: 3
tags: []
user_id: samwise
