artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/e2674fa073844a51a4bb742ac7df2016/artifacts
end_time: 1764100453964
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: e2674fa073844a51a4bb742ac7df2016
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100453409
status: 3
tags: []
user_id: samwise
