artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/eb0a7fb827c44da694bd579a77d481bc/artifacts
end_time: 1765142259515
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: eb0a7fb827c44da694bd579a77d481bc
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765142257975
status: 3
tags: []
user_id: samwise
