artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/6df73052f5ab4ab684baa4293fd2d8df/artifacts
end_time: 1766089146594
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 6df73052f5ab4ab684baa4293fd2d8df
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089144362
status: 3
tags: []
user_id: samwise
