artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/b145f3c4125341e6b94326139ebeae8f/artifacts
end_time: 1764098562127
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: b145f3c4125341e6b94326139ebeae8f
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098560695
status: 3
tags: []
user_id: samwise
