artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/ded0361524204a128338f5fbc2f7a12b/artifacts
end_time: 1764537279915
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: ded0361524204a128338f5fbc2f7a12b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764537278908
status: 3
tags: []
user_id: samwise
