artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/010bc0f15c364370adada7c2b406cfe4/artifacts
end_time: 1764097995039
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 010bc0f15c364370adada7c2b406cfe4
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764097994168
status: 3
tags: []
user_id: samwise
