artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/8e3cb296a0174e46bd9e09a93b313f94/artifacts
end_time: 1764619344817
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 8e3cb296a0174e46bd9e09a93b313f94
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619343163
status: 3
tags: []
user_id: samwise
