artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/9e087cb086c446399fd8b390cbbcba19/artifacts
end_time: 1764624876130
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 9e087cb086c446399fd8b390cbbcba19
run_name: rag_pipeline_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624843276
status: 3
tags: []
user_id: samwise
