artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/ac31a3e9a562449899fa34bef3b23751/artifacts
end_time: 1764619174575
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: ac31a3e9a562449899fa34bef3b23751
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619173917
status: 3
tags: []
user_id: samwise
