artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/315c1f0d61df4934a367e39ce37b057e/artifacts
end_time: 1766089354879
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 315c1f0d61df4934a367e39ce37b057e
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089353601
status: 3
tags: []
user_id: samwise
