artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/3d3840dcb2394a32b14939a6a6aa60a1/artifacts
end_time: 1764100533454
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 3d3840dcb2394a32b14939a6a6aa60a1
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100531810
status: 3
tags: []
user_id: samwise
