artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/76ecb92ce1ec41b8b2eb5e69b6846b7a/artifacts
end_time: 1764099728389
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 76ecb92ce1ec41b8b2eb5e69b6846b7a
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099727340
status: 3
tags: []
user_id: samwise
