artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/ff3e7126505c47fab091f1e69ac1a33e/artifacts
end_time: 1764099227957
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: ff3e7126505c47fab091f1e69ac1a33e
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099226923
status: 3
tags: []
user_id: samwise
