artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/b49eeae63a544e0699422f1b44ef5f1b/artifacts
end_time: 1764095928231
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: b49eeae63a544e0699422f1b44ef5f1b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764095922721
status: 3
tags: []
user_id: samwise
