artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/6b89fddf519e4bf7b7d5ec9f1c5081a3/artifacts
end_time: 1764618665138
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 6b89fddf519e4bf7b7d5ec9f1c5081a3
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764618664518
status: 3
tags: []
user_id: samwise
