artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/430e479b933e40ca85f18e97fffdda63/artifacts
end_time: 1764537277894
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 430e479b933e40ca85f18e97fffdda63
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764537276873
status: 3
tags: []
user_id: samwise
