artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/b726d03ab1534f8798d5aeff133a760d/artifacts
end_time: 1764098082170
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: b726d03ab1534f8798d5aeff133a760d
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098081662
status: 3
tags: []
user_id: samwise
