artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/81ae3c8acea8414a8c3f0195fce6c026/artifacts
end_time: 1764103946378
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 81ae3c8acea8414a8c3f0195fce6c026
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103945192
status: 3
tags: []
user_id: samwise
