artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/d7a2d1d7cccc4b68ab2b7c21e87c7574/artifacts
end_time: 1766089386576
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: d7a2d1d7cccc4b68ab2b7c21e87c7574
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089384232
status: 3
tags: []
user_id: samwise
