artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/b82bb86a9fbb4f4aa2044c4aa93deb85/artifacts
end_time: 1764100057353
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: b82bb86a9fbb4f4aa2044c4aa93deb85
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100056996
status: 3
tags: []
user_id: samwise
