artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/432efb456c9b4c349cf16e05232cdcdd/artifacts
end_time: 1764096960180
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 432efb456c9b4c349cf16e05232cdcdd
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764096956534
status: 3
tags: []
user_id: samwise
