artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/6b9b4424d78c4d419982a0f1ccb19a71/artifacts
end_time: 1764538478903
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 6b9b4424d78c4d419982a0f1ccb19a71
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764538478057
status: 3
tags: []
user_id: samwise
