artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/bfe57898e34246dd8afcc33534ddbc32/artifacts
end_time: 1764624479539
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: bfe57898e34246dd8afcc33534ddbc32
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624478698
status: 3
tags: []
user_id: samwise
