artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/f148474fbdb343d6b4121cf97870c6f7/artifacts
end_time: 1764537033641
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: f148474fbdb343d6b4121cf97870c6f7
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764537032656
status: 3
tags: []
user_id: samwise
