artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/b9b380af6a1e4de7b1bad9b227b4bdfe/artifacts
end_time: 1766088996973
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: b9b380af6a1e4de7b1bad9b227b4bdfe
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766088995156
status: 3
tags: []
user_id: samwise
