artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/4be9e64727e14b8896ef0369bee541d7/artifacts
end_time: 1764538486828
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 4be9e64727e14b8896ef0369bee541d7
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764538485586
status: 3
tags: []
user_id: samwise
