artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/92e419ed1fbc40deafacec79d5e6cc12/artifacts
end_time: 1764624508647
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 92e419ed1fbc40deafacec79d5e6cc12
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624505028
status: 3
tags: []
user_id: samwise
