artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/0d55082beb464c3e83ded748b91d6ecf/artifacts
end_time: 1764098794460
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 0d55082beb464c3e83ded748b91d6ecf
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098793484
status: 3
tags: []
user_id: samwise
