artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/616cf358f5624acdbf9b0226f15e79a0/artifacts
end_time: 1764105311004
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 616cf358f5624acdbf9b0226f15e79a0
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105309583
status: 3
tags: []
user_id: samwise
