artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/ad4c66715d2b40adb76723916f2b42be/artifacts
end_time: 1764096279807
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: ad4c66715d2b40adb76723916f2b42be
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764096273952
status: 3
tags: []
user_id: samwise
