artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/fb1ace1a7a944a6c9da6dbbb0379480c/artifacts
end_time: 1764538279218
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: fb1ace1a7a944a6c9da6dbbb0379480c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764538277289
status: 3
tags: []
user_id: samwise
