artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/c5908659269a4ceb8bb0248f0da5cee1/artifacts
end_time: 1764099764258
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: c5908659269a4ceb8bb0248f0da5cee1
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099763753
status: 3
tags: []
user_id: samwise
