artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/eada800ff78643f38e2b837423ac3e44/artifacts
end_time: 1764099307407
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: eada800ff78643f38e2b837423ac3e44
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099307223
status: 3
tags: []
user_id: samwise
