artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/d7dd2ede66da4111a051ede3044b35bf/artifacts
end_time: 1764623972376
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: d7dd2ede66da4111a051ede3044b35bf
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623971671
status: 3
tags: []
user_id: samwise
