artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/9afb1165f4254a568fb61be7c27d9c09/artifacts
end_time: 1764103750895
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 9afb1165f4254a568fb61be7c27d9c09
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103750379
status: 3
tags: []
user_id: samwise
