artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/a393835dc36b44d79b2e5a2074b11dcb/artifacts
end_time: 1764623566958
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: a393835dc36b44d79b2e5a2074b11dcb
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623564851
status: 3
tags: []
user_id: samwise
