artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/d5f9331eab83405ca9ec028ff6c88251/artifacts
end_time: 1764623962217
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: d5f9331eab83405ca9ec028ff6c88251
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623961684
status: 3
tags: []
user_id: samwise
