artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/19ce75b3e8fd4d6a9a4bd41e8dfb9b8d/artifacts
end_time: 1764098646096
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 19ce75b3e8fd4d6a9a4bd41e8dfb9b8d
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098644599
status: 3
tags: []
user_id: samwise
