artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/c28906e7489b405d8ecdb14549cecbb7/artifacts
end_time: 1764624674477
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: c28906e7489b405d8ecdb14549cecbb7
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624672811
status: 3
tags: []
user_id: samwise
