artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/86d7cf598bc246b287f92316e7e1dffc/artifacts
end_time: 1765140923800
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 86d7cf598bc246b287f92316e7e1dffc
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140923188
status: 3
tags: []
user_id: samwise
