artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/ea8ec3c3c4b741008365652a9d0a2ac9/artifacts
end_time: 1764103316609
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: ea8ec3c3c4b741008365652a9d0a2ac9
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103316122
status: 3
tags: []
user_id: samwise
