artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/cb945a69c0bd428b8b62c0f385c7c101/artifacts
end_time: 1764624514613
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: cb945a69c0bd428b8b62c0f385c7c101
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624513640
status: 3
tags: []
user_id: samwise
