artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/7bfdbe47a56a4e5e8bbad4bc3f36cc89/artifacts
end_time: 1764624062264
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 7bfdbe47a56a4e5e8bbad4bc3f36cc89
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764624061423
status: 3
tags: []
user_id: samwise
