artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/8cdb7268f8fc4c0d897803d16e19d992/artifacts
end_time: 1764538488313
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 8cdb7268f8fc4c0d897803d16e19d992
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764538487450
status: 3
tags: []
user_id: samwise
