artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/eed0e4ba28db45fea67a9607c5cb320c/artifacts
end_time: 1765141375118
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: eed0e4ba28db45fea67a9607c5cb320c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765141374519
status: 3
tags: []
user_id: samwise
