artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/87636f49cf7b463bbdb7efce56be3c7e/artifacts
end_time: 1764103841172
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 87636f49cf7b463bbdb7efce56be3c7e
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764103840698
status: 3
tags: []
user_id: samwise
