artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/25aaacf5bc7c4d038e2b49b234210cbf/artifacts
end_time: 1764619240382
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 25aaacf5bc7c4d038e2b49b234210cbf
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619239507
status: 3
tags: []
user_id: samwise
