artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/811d69c0b86146f1b3230cc2fbdbfe55/artifacts
end_time: 1764099747510
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 811d69c0b86146f1b3230cc2fbdbfe55
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099746627
status: 3
tags: []
user_id: samwise
