artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/3c2b5ff2777e45739c28a96dc61cc351/artifacts
end_time: 1764619538951
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 3c2b5ff2777e45739c28a96dc61cc351
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619538050
status: 3
tags: []
user_id: samwise
