artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/cdbb29e1da3a479cb8bb7b9f2d09969e/artifacts
end_time: 1764104994608
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: cdbb29e1da3a479cb8bb7b9f2d09969e
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764104993912
status: 3
tags: []
user_id: samwise
