artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/a88e16896cf443c2b5c18f0c92be6462/artifacts
end_time: 1764100698084
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: a88e16896cf443c2b5c18f0c92be6462
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100696971
status: 3
tags: []
user_id: samwise
