artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/cf9ff0f7cd2f4b8eb2873c7b65e56144/artifacts
end_time: 1764095817350
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: cf9ff0f7cd2f4b8eb2873c7b65e56144
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764095816794
status: 3
tags: []
user_id: samwise
