artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/bc77e4f38ea94bdb95a87d4ba5c9ea6d/artifacts
end_time: 1764100585039
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: bc77e4f38ea94bdb95a87d4ba5c9ea6d
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100584037
status: 3
tags: []
user_id: samwise
