artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/ba1d3b9ce43a44edbb624af34cb94236/artifacts
end_time: 1764097063812
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: ba1d3b9ce43a44edbb624af34cb94236
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764097063197
status: 3
tags: []
user_id: samwise
