artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/f7cf0a8e6e3a4f118d3a0170df5f3487/artifacts
end_time: 1766089296754
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: f7cf0a8e6e3a4f118d3a0170df5f3487
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089295737
status: 3
tags: []
user_id: samwise
