artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/f6d92e7136dc44e293b49cae004670b2/artifacts
end_time: 1764096942557
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: f6d92e7136dc44e293b49cae004670b2
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764096941625
status: 3
tags: []
user_id: samwise
