artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/5e4ab8982ded4a5fa7f7877874e40e8d/artifacts
end_time: 1766089263057
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 5e4ab8982ded4a5fa7f7877874e40e8d
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089262305
status: 3
tags: []
user_id: samwise
