artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/106cce4d0c6e460e9ca4e414097df667/artifacts
end_time: 1765140621434
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 106cce4d0c6e460e9ca4e414097df667
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140620288
status: 3
tags: []
user_id: samwise
