artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/781a955c590b44b69f16e5db2c9c45f2/artifacts
end_time: 1764099578971
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 781a955c590b44b69f16e5db2c9c45f2
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099578566
status: 3
tags: []
user_id: samwise
