artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/606b13df9fca4736a90631b70a6549fd/artifacts
end_time: 1764619724828
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 606b13df9fca4736a90631b70a6549fd
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619724296
status: 3
tags: []
user_id: samwise
