artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/805c03258a6e4e7b8e7390a2eb699a3c/artifacts
end_time: 1764098362888
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 805c03258a6e4e7b8e7390a2eb699a3c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098362169
status: 3
tags: []
user_id: samwise
