artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/9b1fc48f87b04805869dd4f4b130c62f/artifacts
end_time: 1764099384122
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 9b1fc48f87b04805869dd4f4b130c62f
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099383595
status: 3
tags: []
user_id: samwise
