artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/32c8e6acc68f4b7c9e6b94d99545c4a8/artifacts
end_time: 1764619102907
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 32c8e6acc68f4b7c9e6b94d99545c4a8
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764619102007
status: 3
tags: []
user_id: samwise
