artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/9ebcea8dc01b40ce80234a59ed2f68de/artifacts
end_time: 1764097795103
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 9ebcea8dc01b40ce80234a59ed2f68de
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764097793685
status: 3
tags: []
user_id: samwise
