artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/63a8831d251a4460ade961f447a61daf/artifacts
end_time: 1764104094485
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 63a8831d251a4460ade961f447a61daf
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764104093026
status: 3
tags: []
user_id: samwise
