artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/527d90dd162b4b979e07b7e6c96d9d46/artifacts
end_time: 1764099752202
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 527d90dd162b4b979e07b7e6c96d9d46
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099751637
status: 3
tags: []
user_id: samwise
