artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/7f57521b45d24040a451ef86af7f7dd7/artifacts
end_time: 1764618635018
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 7f57521b45d24040a451ef86af7f7dd7
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764618634421
status: 3
tags: []
user_id: samwise
