artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/9138facb31a943cebb7cc5aa421ef50d/artifacts
end_time: 1764623412969
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 9138facb31a943cebb7cc5aa421ef50d
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623411395
status: 3
tags: []
user_id: samwise
