artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/56d27c86510544eb91acaf38c086eb38/artifacts
end_time: 1765140262690
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 56d27c86510544eb91acaf38c086eb38
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1765140262219
status: 3
tags: []
user_id: samwise
