artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/b98e919c1da4468da0d9e7dd3c6e878b/artifacts
end_time: 1764096446158
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: b98e919c1da4468da0d9e7dd3c6e878b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764096445528
status: 3
tags: []
user_id: samwise
