artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/a5d4b75093a44fd6960958b568e3fc9c/artifacts
end_time: 1764095909657
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: a5d4b75093a44fd6960958b568e3fc9c
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764095908756
status: 3
tags: []
user_id: samwise
