artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/0db84b3fa7b84c829e0d5067fd0cc39e/artifacts
end_time: 1764100737340
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 0db84b3fa7b84c829e0d5067fd0cc39e
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100736339
status: 3
tags: []
user_id: samwise
