artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/d395fe507e3e46e2b09ef946fb88a93b/artifacts
end_time: 1764623666538
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: d395fe507e3e46e2b09ef946fb88a93b
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764623665031
status: 3
tags: []
user_id: samwise
