artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/84f4843df9af4920a3d0ad1148adde32/artifacts
end_time: 1764105050396
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 84f4843df9af4920a3d0ad1148adde32
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764105049524
status: 3
tags: []
user_id: samwise
