artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/f1c47cabd2ba4758aecb962b828912cb/artifacts
end_time: 1764099444217
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: f1c47cabd2ba4758aecb962b828912cb
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099443704
status: 3
tags: []
user_id: samwise
