artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/12ce3fff12ef417dacf8de9d34235dfd/artifacts
end_time: 1764100721513
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 12ce3fff12ef417dacf8de9d34235dfd
run_name: embed_documents
source_name: ''
source_type: 4
source_version: ''
start_time: 1764100720929
status: 3
tags: []
user_id: samwise
