artifact_uri: /home/samwise/projects/llm_career_assistant/${MLFLOW_TRACKING_URI:-http:/mlflow:5000}/105988660429923401/01a267e224ec400683fd49683a9d0bb4/artifacts
end_time: 1764704968941
entry_point_name: ''
experiment_id: '105988660429923401'
lifecycle_stage: active
run_id: 01a267e224ec400683fd49683a9d0bb4
run_name: vector_store_search
source_name: ''
source_type: 4
source_version: ''
start_time: 1764704968365
status: 3
tags: []
user_id: samwise
